[ec2_servers]
51.20.35.90 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ansible-mayur-key.pem instance_id="Instance-1 (eu-north-1a)"
13.61.32.2 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ansible-mayur-key.pem instance_id="Instance-2 (eu-north-1b)"